apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.app }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: PORT
      port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP
    - name: AUTHORIZED_PORT
      port: {{ .Values.authorized_port }}
      targetPort: {{ .Values.authorized_port }}
      protocol: TCP
  selector:
    app: {{ .Values.app }}
    release: {{ .Release.Name }}
