resolver: lts-15.6
packages:
- casa-types
- casa-server
- casa-client

extra-deps:
- git: https://github.com/commercialhaskell/stack.git
  commit: 2e88174e738f74efd2a0c9f21e95cc109ad2cd62
- git: https://github.com/commercialhaskell/pantry.git
  commit: de8a0b5f88e9974fafb4a6ed5835d1da8f821d80
- git: https://github.com/chrisdone/yesod-lucid.git
  commit: cde88d0736a44163be70044a109798f578151db3
- base16-bytestring-1.0.0.0@rev:0
