spec-version: 0.36.0

name: casa-client
version: 0.0.3
synopsis: Client for Casa
description: |
  Client for Casa (Content-Addressable Storage Archive). See
  <https://casa.stackage.org/>
copyright:
- 2018-2019 FP Complete
- 2024-2025 Haskell Foundation
author: Chris Done
maintainer:
- Chris Done <chrisdone@fpcomplete.com>
- Mike Pilgrem <public@pilgrem.com>
category: Development
extra-source-files:
- CHANGELOG.md

github: commercialhaskell/casa/casa-client

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - base >= 4.8 && < 5
  - aeson >= 1.5.6.0
  - attoparsec >= 0.13.2.5
  - base16-bytestring >= 1.0.2.0
  - bytestring >= 0.10.12.0
  - casa-types >= 0.0.2
  - conduit >= 1.3.4.2
  - conduit-extra >= 1.3.5
  - crypton >= 0.34
  - exceptions >= 0.10.4
  - http-conduit >= 2.3.8
  - http-types >= 0.12.3
  - memory >= 0.15.0
  - network-uri >= 2.6.4.1
  - resourcet >= 1.2.4.3
  - template-haskell >= 2.16.0.0
  - text >= 1.2.4.1
  - th-lift >= 0.8.2
  - unliftio-core >= 0.2.0.1
  - unordered-containers >= 0.2.16.0
